import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { LayoutDashboard, ListTodo, Timer, ShoppingBag, History, Settings2, Plus, ArrowUpRight, ArrowRight, Check, Circle, MoreHorizontal, Search, SlidersHorizontal, Sparkles, Flame, Play, Pause, RotateCcw, ChevronDown, X, Pencil, Trash2, CalendarDays, PanelLeftClose, Menu, ExternalLink, Download } from 'lucide-react';
import './style.css';

const KEY='study-spark-v1';
const initialState={stars:0,tasks:[],rewards:[],transactions:[],profile:{name:''},pomodoro:{completedToday:0,day:new Date().toDateString(),timer:{mode:'work',remainingSeconds:1500,endAt:null,running:false}},settings:{work:25,break:5,pomoReward:25,localWarningDismissed:false}};
function load(){try{const v=JSON.parse(localStorage.getItem(KEY));if(!v)return initialState;
 // Clear the original sample content once, while preserving any data the user has since created.
 const oldSample=v.transactions?.some(t=>t.id==='h1'&&t.title==='Стартовый бонус')&&['t1','t2','t3','t4'].every(id=>v.tasks?.some(t=>t.id===id))&&['r1','r2','r3','r4'].every(id=>v.rewards?.some(r=>r.id===id));
 if(oldSample){localStorage.removeItem(KEY);return initialState}
 return {...initialState,...v,profile:{...initialState.profile,...v?.profile},settings:{...initialState.settings,...v?.settings},pomodoro:{...initialState.pomodoro,...v?.pomodoro,timer:{...initialState.pomodoro.timer,...v?.pomodoro?.timer}},tasks:Array.isArray(v.tasks)?v.tasks:[],rewards:Array.isArray(v.rewards)?v.rewards:[],transactions:Array.isArray(v.transactions)?v.transactions:[]}
}catch{return initialState}}
const levels=[0,1000,2500,5000,10000];
const fmt=n=>new Intl.NumberFormat('ru-RU').format(n);
function App(){
 const [data,setData]=useState(load);
 const storedTimer=data.pomodoro.timer||{mode:'work',remainingSeconds:data.settings.work*60,endAt:null,running:false};
 const [page,setPage]=useState('home'),[modal,setModal]=useState(()=>load().profile.name?null:{type:'profile',first:true}),[toast,setToast]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState('Все'),[sort,setSort]=useState('По умолчанию'),[menu,setMenu]=useState(false),[profileMenu,setProfileMenu]=useState(false),[installPrompt,setInstallPrompt]=useState(null),[isInstalled,setIsInstalled]=useState(()=>typeof window!=='undefined'&&(window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone===true));
 const [seconds,setSeconds]=useState(()=>storedTimer.endAt?Math.max(0,Math.ceil((storedTimer.endAt-Date.now())/1000)):storedTimer.remainingSeconds);
 const [timerMode,setTimerMode]=useState(storedTimer.mode||'work'),[endAt,setEndAt]=useState(storedTimer.endAt||null),[running,setRunning]=useState(Boolean(storedTimer.running));
 const [rewardCategory,setRewardCategory]=useState('Все');
 useEffect(()=>localStorage.setItem(KEY,JSON.stringify(data)),[data]);
 useEffect(()=>{
  if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(error=>console.warn('Service worker registration failed',error));
  const promptInstall=event=>{event.preventDefault();setInstallPrompt(event)};
  const installed=()=>{setIsInstalled(true);setInstallPrompt(null);notify('Study Spark установлено на устройство')};
  window.addEventListener('beforeinstallprompt',promptInstall);window.addEventListener('appinstalled',installed);
  return()=>{window.removeEventListener('beforeinstallprompt',promptInstall);window.removeEventListener('appinstalled',installed)}
 },[]);
 useEffect(()=>{if(!running||!endAt)return;let finished=false;const tick=()=>{const left=Math.max(0,Math.ceil((endAt-Date.now())/1000));setSeconds(left);if(left>0||finished)return;finished=true;const worked=timerMode==='work',nextMode=worked?'break':'work',nextSeconds=(worked?data.settings.break:data.settings.work)*60,today=new Date().toDateString();setRunning(false);setEndAt(null);setTimerMode(nextMode);setSeconds(nextSeconds);setData(d=>({...d,...(worked?{stars:d.stars+d.settings.pomoReward,transactions:[{id:crypto.randomUUID(),title:'Завершена Pomodoro',amount:d.settings.pomoReward,type:'earn',date:Date.now()},...d.transactions]}:{}),pomodoro:{...d.pomodoro,...(worked?{completedToday:(d.pomodoro.day===today?d.pomodoro.completedToday:0)+1,day:today}:{}),timer:{mode:nextMode,remainingSeconds:nextSeconds,endAt:null,running:false}}}));notify(worked?`+${data.settings.pomoReward} ⭐ за фокус!`:'Перерыв завершён — время вернуться!')};tick();const id=setInterval(tick,1000);document.addEventListener('visibilitychange',tick);window.addEventListener('focus',tick);return()=>{clearInterval(id);document.removeEventListener('visibilitychange',tick);window.removeEventListener('focus',tick)}},[running,endAt,timerMode,data.settings.work,data.settings.break,data.settings.pomoReward]);
 const notify=s=>{setToast(s);setTimeout(()=>setToast(''),2800)};
 const earned=data.transactions.filter(t=>t.type==='earn').reduce((a,t)=>a+t.amount,0);const level=levels.reduce((a,v,i)=>earned>=v?i:a,0),next=levels[Math.min(level+1,levels.length-1)],progress=level===levels.length-1?100:Math.min(100,((earned-levels[level])/(next-levels[level]))*100);
 const completed=data.tasks.filter(t=>t.status==='completed').length,active=data.tasks.filter(t=>t.status==='active').length;
 const go=p=>{setPage(p);setMenu(false)};
 const storeTimer=(mode,remainingSeconds,target,runningNow)=>setData(d=>({...d,pomodoro:{...d.pomodoro,timer:{mode,remainingSeconds,endAt:target,running:runningNow}}}));
 const toggleTimer=()=>{if(running){const left=Math.max(0,Math.ceil(((endAt||Date.now())-Date.now())/1000));setRunning(false);setEndAt(null);setSeconds(left);storeTimer(timerMode,left,null,false)}else{const target=Date.now()+seconds*1000;setEndAt(target);setRunning(true);storeTimer(timerMode,seconds,target,true)}};
 const setMode=mode=>{const length=(mode==='work'?data.settings.work:data.settings.break)*60;setRunning(false);setEndAt(null);setTimerMode(mode);setSeconds(length);storeTimer(mode,length,null,false)};
 const resetTimer=()=>{const length=(timerMode==='work'?data.settings.work:data.settings.break)*60;setRunning(false);setEndAt(null);setSeconds(length);storeTimer(timerMode,length,null,false)};
 const startInstall=async()=>{setProfileMenu(false);if(installPrompt){await installPrompt.prompt();await installPrompt.userChoice;setInstallPrompt(null)}else setModal({type:'install'})};
 const completeTask=id=>{const task=data.tasks.find(t=>t.id===id);if(!task||task.status==='completed')return;setData(d=>({...d,stars:d.stars+task.reward,tasks:d.tasks.map(t=>t.id===id?{...t,status:'completed',completedAt:Date.now()}:t),transactions:[{id:crypto.randomUUID(),title:`Выполнено задание: ${task.title}`,amount:task.reward,type:'earn',date:Date.now()},...d.transactions]}));notify(`Отличная работа! +${task.reward} ⭐`)};
 const buyReward=r=>{if(data.stars<r.price){notify(`Не хватает ${fmt(r.price-data.stars)} ⭐`);return}setData(d=>({...d,stars:d.stars-r.price,transactions:[{id:crypto.randomUUID(),title:`Куплена награда: ${r.name}`,amount:r.price,type:'spend',date:Date.now()},...d.transactions]}));setModal({type:'purchaseSuccess',reward:r})};
 const nav=[['home','Обзор',LayoutDashboard],['tasks','Задания',ListTodo],['pomodoro','Pomodoro',Timer],['shop','Магазин',ShoppingBag],['history','История',History]];
 const recent=data.transactions.slice(0,4), filteredTasks=data.tasks.filter(t=>(filter==='Все'||(filter==='В процессе'?t.status==='active':'completed'))&&t.title.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='По сложности'?b.reward-a.reward:sort==='По дедлайну'?(a.due||'9999').localeCompare(b.due||'9999'):b.created-a.created);
 const dayCount=data.pomodoro.day===new Date().toDateString()?data.pomodoro.completedToday:0;
 return <div className="app-shell"><aside className={`sidebar ${menu?'open':''}`}><div className="brand"><div className="brand-mark"><Sparkles size={19}/></div><span>study<span className="brand-light">spark</span></span><button className="side-collapse" onClick={()=>setMenu(false)}><PanelLeftClose size={17}/></button></div><div className="side-label">МЕНЮ</div><nav>{nav.map(([id,label,Icon])=><button key={id} className={`nav-item ${page===id?'active':''}`} onClick={()=>go(id)}><Icon size={18}/><span>{label}</span>{id==='tasks'&&active>0&&<b className="nav-count">{active}</b>}</button>)}</nav><div className="sidebar-bottom"><div className="streak-card"><div className="streak-icon"><Flame size={18}/></div><div><strong>Твой темп</strong><small>Каждый шаг важен ✨</small></div></div><div className="profile-menu-wrap"><div className="profile"><button className="profile-identity" onClick={()=>setModal({type:'profile'})}><div className="avatar">{data.profile.name?.trim()?.charAt(0)?.toUpperCase()||'+'}</div><div className="profile-text"><b>{data.profile.name||'Добавить имя'}</b><span>Профиль</span></div></button><button className="icon-btn profile-more" aria-label="Меню профиля" onClick={()=>setProfileMenu(v=>!v)}><MoreHorizontal size={18}/></button></div>{profileMenu&&<div className="profile-dropdown"><button onClick={()=>{setModal({type:'settings'});setProfileMenu(false)}}><Settings2 size={15}/> Настройки</button><button onClick={startInstall} disabled={isInstalled}><Download size={15}/> {isInstalled?'Приложение установлено':'Скачать приложение'}</button><button onClick={()=>{setModal({type:'profile'});setProfileMenu(false)}}><Pencil size={15}/> Изменить имя</button><button onClick={()=>{setModal({type:'support'});setProfileMenu(false)}}><ExternalLink size={15}/> Поддержать проект</button></div>}</div></div></aside>
 <main className="main"><header className="topbar"><button className="mobile-menu icon-btn" onClick={()=>setMenu(!menu)}><Menu size={20}/></button><div className="breadcrumbs">Пространство <span>/</span> <b>{nav.find(n=>n[0]===page)?.[1]||'Обзор'}</b></div><div className="top-actions"><div className="balance-pill"><span>⭐</span><b>{fmt(data.stars)}</b><small>звёзд</small></div><button className="icon-btn settings-btn" onClick={()=>setModal({type:'settings'})}><Settings2 size={18}/></button><button className="avatar top-avatar" onClick={()=>setModal({type:'profile'})}>{data.profile.name?.trim()?.charAt(0)?.toUpperCase()||'+'}</button></div></header><div className="content">{!data.settings.localWarningDismissed&&<div className="local-warning"><div className="local-warning-icon">i</div><p><b>Данные хранятся в этом браузере.</b> Даже если приложение размещено на Vercel, информация не синхронизируется между устройствами и может быть удалена при очистке данных сайта.</p><button aria-label="Закрыть предупреждение" onClick={()=>setData(d=>({...d,settings:{...d.settings,localWarningDismissed:true}}))}><X size={16}/></button></div>}
 {page==='home'&&<><div className="welcome-row"><div><div className="eyebrow"><span className="eyebrow-dot"/> ВТОРНИК, 6 ОКТЯБРЯ</div><h1>Хороший день{data.profile.name?`, ${data.profile.name}`:''} <span className="wave">✦</span></h1><p className="subtitle">Маленькие шаги сегодня — большие результаты завтра.</p></div><button className="button button-dark" onClick={()=>{setModal({type:'task'});}}> <Plus size={17}/> Новое задание</button></div>
 <section className="hero-card"><div className="hero-copy"><div className="hero-kicker"><Sparkles size={14}/> ТВОЙ ПРОГРЕСС</div><h2>Каждая звезда<br/>приближает к цели.</h2><p>Продолжай в своём темпе — у тебя отлично получается.</p><div className="level-line"><span>Уровень {level+1}</span><span>{fmt(earned-levels[level])} <i>/</i> {fmt(next-levels[level])} ⭐</span></div><div className="progress-track"><div style={{width:`${progress}%`}}/></div><button className="hero-link" onClick={()=>go('shop')}>Посмотреть награды <ArrowRight size={15}/></button></div><div className="hero-art"><div className="orb orb-one"/><div className="orb orb-two"/><div className="star-big">✦</div><div className="floating-star fs-one">✧</div><div className="floating-star fs-two">✦</div><div className="art-caption">LEVEL <b>{level+1}</b></div></div></section>
 <section className="stats-grid"><Stat icon={Check} label="Выполнено заданий" value={completed} extra="Так держать!" tone="green"/><Stat icon={ListTodo} label="В процессе" value={active} extra="Пора за дело" tone="blue"/><Stat icon={Timer} label="Фокус-сессий сегодня" value={dayCount} extra="Каждая минута важна" tone="orange"/></section>
 <div className="section-heading"><div><h2>Твой план</h2><p>Всё начинается с одного шага</p></div><button className="text-link" onClick={()=>go('tasks')}>Все задания <ArrowRight size={15}/></button></div>
 <div className="dashboard-columns"><div className="panel task-panel"><div className="panel-head"><h3>Задания на сегодня</h3><span className="soft-count">{active} активных</span></div>{data.tasks.filter(t=>t.status==='active').slice(0,3).map(t=><TaskRow key={t.id} task={t} complete={completeTask} edit={()=>setModal({type:'task',task:t})} remove={()=>removeTask(t.id)}/>)}{active===0&&<div className="empty">Отлично! Все задания выполнены. <button onClick={()=>setModal({type:'task'})}>Добавить новое</button></div>}<button className="panel-footer-link" onClick={()=>go('tasks')}>Перейти к заданиям <ArrowRight size={14}/></button></div>
 <div className="right-stack"><div className="focus-card"><div className="focus-top"><div><span className="focus-label">ВРЕМЯ ДЛЯ ФОКУСА</span><h3>Одна задача за раз.</h3></div><div className="focus-icon"><Timer size={19}/></div></div><div className="focus-bottom"><div className="mini-timer"><span className="mini-dot"/>25:00</div><button className="round-arrow" onClick={()=>go('pomodoro')}><ArrowUpRight size={19}/></button></div></div><div className="recent-panel"><div className="panel-head"><h3>Последние события</h3><button className="dots" onClick={()=>go('history')}><MoreHorizontal size={18}/></button></div>{recent.slice(0,3).map(t=><TransactionRow key={t.id} item={t} compact/>)}{recent.length===0&&<div className="muted-empty">Пока нет событий</div>}</div></div></div>
 </>}
 {page==='tasks'&&<><PageTitle eyebrow="ТВОЙ СПИСОК" title="Задания" subtitle="Планируй, делай и отмечай свои победы." action={<button className="button button-dark" onClick={()=>setModal({type:'task'})}><Plus size={17}/> Добавить задание</button>}/><div className="toolbar"><div className="searchbox"><Search size={17}/><input placeholder="Найти задание..." value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="select-wrap"><SlidersHorizontal size={16}/><select value={filter} onChange={e=>setFilter(e.target.value)}><option>Все</option><option>В процессе</option><option>Выполнено</option></select><ChevronDown size={14}/></div><div className="select-wrap"><select value={sort} onChange={e=>setSort(e.target.value)}><option>По умолчанию</option><option>По сложности</option><option>По дедлайну</option></select><ChevronDown size={14}/></div></div><div className="task-list panel">{filteredTasks.length?filteredTasks.map(t=><TaskRow key={t.id} task={t} complete={completeTask} edit={()=>setModal({type:'task',task:t})} remove={()=>removeTask(t.id)}/>):<div className="empty">Заданий пока нет. <button onClick={()=>setModal({type:'task'})}>Создать первое</button></div>}</div></>}
 {page==='pomodoro'&&<><PageTitle eyebrow="УЧИСЬ С ПЕРЕРЫВАМИ" title="Pomodoro" subtitle="Фокусируйся на важном, не забывая отдыхать."/><div className="pomo-layout"><div className="pomo-main panel"><div className="mode-switch"><button className={timerMode==='work'?'selected':''} onClick={()=>setMode('work')}>Фокус</button><button className={timerMode==='break'?'selected':''} onClick={()=>setMode('break')}>Перерыв</button></div><div className="timer-ring"><svg viewBox="0 0 300 300"><circle className="ring-bg" cx="150" cy="150" r="132"/><circle className="ring-progress" cx="150" cy="150" r="132" style={{strokeDashoffset:830*(1-seconds/((timerMode==='work'?data.settings.work:data.settings.break)*60))}}/></svg><div className="timer-display"><span>{timerMode==='work'?'ВРЕМЯ ФОКУСА':'ВРЕМЯ ОТДЫХА'}</span><strong>{String(Math.floor(seconds/60)).padStart(2,'0')}:{String(seconds%60).padStart(2,'0')}</strong><small>{running?'Ты справляешься отлично': 'Готов начать?'}</small></div></div><div className="timer-controls"><button className="button button-dark timer-start" onClick={toggleTimer}>{running?<Pause size={17}/>:<Play size={17} fill="currentColor"/>}{running?'Пауза':'Начать фокус'}</button><button className="reset-btn" onClick={resetTimer}><RotateCcw size={17}/></button></div><div className="pomo-tip"><Sparkles size={16}/><span>После каждой завершённой сессии ты получишь <b>+{data.settings.pomoReward} ⭐</b></span></div></div><div className="pomo-side"><div className="panel today-panel"><div className="today-icon"><Flame size={20}/></div><span>СЕГОДНЯ</span><strong>{dayCount} <small>сессий</small></strong><p>Каждый фокус — это инвестиция в себя.</p><div className="session-dots">{Array.from({length:4},(_,i)=><span key={i} className={i<dayCount?'filled':''}>✦</span>)}</div></div><div className="panel routine-panel"><div className="panel-head"><h3>Твой ритм</h3><button className="icon-btn tiny" onClick={()=>setModal({type:'settings'})}><Settings2 size={16}/></button></div><div className="routine-row"><span className="routine-dot work-dot"/>Фокус <b>{data.settings.work} мин</b></div><div className="routine-row"><span className="routine-dot break-dot"/>Перерыв <b>{data.settings.break} мин</b></div><div className="routine-row"><span className="routine-dot star-dot"/>Награда <b>+{data.settings.pomoReward} ⭐</b></div></div></div></div></>}
 {page==='shop'&&<><PageTitle eyebrow="ТЫ ЭТО ЗАСЛУЖИЛ" title="Магазин наград" subtitle="Обменивай звёзды на маленькие радости." action={<button className="button button-outline" onClick={()=>setModal({type:'manage'})}><Settings2 size={16}/> Управление магазином</button>}/><div className="shop-banner"><div className="shop-banner-icon">✳</div><div><span>ТВОЙ БАЛАНС</span><h2>{fmt(data.stars)} <small>⭐</small></h2><p>Звёзды превращаются в то, что радует.</p></div><div className="banner-decoration">✦</div></div><div className="shop-controls"><div className="category-pills">{['Все',...new Set(data.rewards.map(r=>r.category).filter(Boolean))].map(c=><button key={c} className={rewardCategory===c?'chosen':''} onClick={()=>setRewardCategory(c)}>{c}</button>)}</div><span className="item-count">{data.rewards.filter(r=>rewardCategory==='Все'||r.category===rewardCategory).length} награды</span></div><div className="reward-grid">{data.rewards.filter(r=>rewardCategory==='Все'||r.category===rewardCategory).map(r=><div className="reward-card" key={r.id}><div className="reward-art"><span>{r.emoji||'🎁'}</span><div className="reward-category">{r.category||'Награда'}</div><button className="reward-edit" title="Редактировать" onClick={()=>setModal({type:'reward',reward:r})}><Pencil size={14}/></button></div><div className="reward-info"><h3>{r.name}</h3><p>{r.description}</p><div className="reward-buy"><strong>⭐ {fmt(r.price)}</strong><button disabled={data.stars<r.price} onClick={()=>buyReward(r)}>{data.stars>=r.price?'Обменять':'Ещё '+fmt(r.price-data.stars)} <ArrowRight size={14}/></button></div></div></div>)}{data.rewards.length===0&&<div className="shop-empty"><span>✦</span><h3>Твой магазин пока пуст</h3><p>Добавь награды, на которые захочется копить звёзды.</p><button className="button button-dark" onClick={()=>setModal({type:'reward'})}><Plus size={16}/> Добавить первую награду</button></div>}<button className="add-reward-card" onClick={()=>setModal({type:'reward'})}><span><Plus size={22}/></span><b>Добавить награду</b><small>Создай свою мотивацию</small></button></div></>}
 {page==='history'&&<><PageTitle eyebrow="ТВОЙ ПУТЬ" title="История" subtitle="Каждый шаг и каждая звезда — часть твоего прогресса."/><div className="history-summary"><div><span>ЗАРАБОТАНО</span><b className="positive">+{fmt(earned)} ⭐</b></div><div><span>ПОТРАЧЕНО</span><b className="negative">−{fmt(data.transactions.filter(t=>t.type==='spend').reduce((a,t)=>a+t.amount,0))} ⭐</b></div><div><span>ОПЕРАЦИЙ</span><b>{data.transactions.length}</b></div></div><div className="panel history-panel"><div className="panel-head"><h3>Все операции</h3><span className="soft-count">{data.transactions.length} записей</span></div>{data.transactions.length?data.transactions.map(t=><TransactionRow key={t.id} item={t}/>):<div className="empty">История пока пуста</div>}</div></>}
 </div></main>{menu&&<div className="mobile-shade" onClick={()=>setMenu(false)}/>} {toast&&<div className="toast"><Sparkles size={17}/>{toast}</div>}{modal&&<Modal key={`${modal.type}-${modal.task?.id||modal.reward?.id||''}`} modal={modal} close={()=>setModal(null)} data={data} setData={setData} notify={notify} openReward={reward=>setModal({type:'reward',reward})} addReward={()=>setModal({type:'reward'})}/> }</div>;
 function removeTask(id){if(confirm('Удалить это задание?'))setData(d=>({...d,tasks:d.tasks.filter(t=>t.id!==id)}))}
}
function Stat({icon:Icon,label,value,extra,tone}){return <div className="stat-card"><div className={`stat-icon ${tone}`}><Icon size={18}/></div><div className="stat-copy"><span>{label}</span><div><strong>{value}</strong><small>{extra}</small></div></div><ArrowUpRight className="stat-arrow" size={17}/></div>}
function PageTitle({eyebrow,title,subtitle,action}){return <div className="page-title-row"><div><div className="eyebrow"><span className="eyebrow-dot"/>{eyebrow}</div><h1>{title}</h1><p className="subtitle">{subtitle}</p></div>{action}</div>}
function TaskRow({task,complete,edit,remove}){const due=task.due?new Date(`${task.due}T12:00:00`).toLocaleDateString('ru-RU',{day:'numeric',month:'short'}):null;return <div className={`task-row ${task.status==='completed'?'is-done':''}`}><button className={`task-check ${task.status==='completed'?'checked':''}`} onClick={()=>task.status!=='completed'&&complete(task.id)}>{task.status==='completed'?<Check size={14}/>:<Circle size={18}/>}</button><div className="task-main"><h4>{task.title}</h4>{task.description&&<p>{task.description}</p>}<div className="task-meta"><span className={`difficulty ${task.difficulty==='Лёгкое'?'easy':task.difficulty==='Среднее'?'medium':task.difficulty==='Сложное'?'hard':'very-hard'}`}>{task.difficulty}</span>{due&&<span className="due"><CalendarDays size={13}/>{due}</span>}</div></div><div className="task-reward">⭐ {task.reward}</div><div className="task-actions">{task.status==='active'&&<button className="complete-btn" onClick={()=>complete(task.id)}>Выполнить</button>}<button className="icon-btn tiny" onClick={edit}><Pencil size={15}/></button><button className="icon-btn tiny danger-hover" onClick={remove}><Trash2 size={15}/></button></div></div>}
function TransactionRow({item,compact}){const positive=item.type==='earn';return <div className={`transaction-row ${compact?'compact':''}`}><div className={`transaction-icon ${positive?'earned':'spent'}`}>{positive?<ArrowDownIcon/>:<ShoppingBag size={16}/>}</div><div className="transaction-info"><b>{item.title}</b><span>{new Date(item.date).toLocaleString('ru-RU',{day:'numeric',month:'long',hour:'2-digit',minute:'2-digit'})}</span></div><strong className={positive?'positive':'negative'}>{positive?'+':'−'}{fmt(item.amount)} ⭐</strong></div>}
function ArrowDownIcon(){return <ArrowUpRight size={16} style={{transform:'rotate(180deg)'}}/>}
function Modal({modal,close,data,setData,openReward,addReward}){const [form,setForm]=useState(modal.type==='task'?{title:modal.task?.title||'',description:modal.task?.description||'',difficulty:modal.task?.difficulty||'Среднее',reward:modal.task?.reward||100,due:modal.task?.due||''}:modal.type==='reward'?{name:modal.reward?.name||'',description:modal.reward?.description||'',price:modal.reward?.price||500,emoji:modal.reward?.emoji||'🎁',category:modal.reward?.category||'Маленькие радости'}:modal.type==='settings'?{...data.settings}:modal.type==='profile'?{name:data.profile.name||''}:{});
 const saveTask=e=>{e.preventDefault();const d={id:modal.task?.id||crypto.randomUUID(),...form,reward:Number(form.reward),status:modal.task?.status||'active',created:modal.task?.created||Date.now()};setData(x=>({...x,tasks:modal.task?x.tasks.map(t=>t.id===d.id?d:t):[d,...x.tasks]}));close()};
 const saveReward=e=>{e.preventDefault();const d={id:modal.reward?.id||crypto.randomUUID(),...form,price:Number(form.price)};setData(x=>({...x,rewards:modal.reward?x.rewards.map(t=>t.id===d.id?d:t):[d,...x.rewards]}));close()};
 const saveSettings=e=>{e.preventDefault();setData(d=>({...d,settings:{...d.settings,work:Number(form.work),break:Number(form.break),pomoReward:Number(form.pomoReward)}}));close()};
 const saveProfile=e=>{e.preventDefault();setData(d=>({...d,profile:{...d.profile,name:form.name.trim()}}));close()};
 if(modal.type==='install')return <div className="modal-backdrop" onClick={close}><div className="modal install-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={close}><X size={18}/></button><div className="support-icon">✦</div><div className="eyebrow centered">STUDY SPARK ДЛЯ ТВОЕГО УСТРОЙСТВА</div><h2>Установить приложение</h2><p>Добавь Study Spark на главный экран и открывай его как обычное приложение. После первого посещения оно также сможет запускаться без интернета.</p><div className="install-steps"><div><b>iPhone или iPad</b><span>Открой сайт в Safari, нажми «Поделиться» → «На экран Домой».</span></div><div><b>Android</b><span>В Chrome открой меню ⋮ и выбери «Установить приложение» или «Добавить на главный экран».</span></div><div><b>Компьютер</b><span>В Chrome или Edge нажми значок установки рядом с адресной строкой либо выбери «Установить Study Spark» в меню браузера.</span></div></div><button className="button button-outline full" onClick={close}>Понятно</button></div></div>;
 if(modal.type==='support')return <div className="modal-backdrop" onClick={close}><div className="modal support-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={close}><X size={18}/></button><div className="support-icon">✦</div><div className="eyebrow centered">STUDY SPARK</div><h2>Поддержать проект</h2><p>Если Study Spark помогает тебе учиться, поддержи его развитие. Любой вклад поможет добавлять новые возможности. Спасибо, что ты с нами!</p><a className="button button-dark full" href="https://buymeacoffee.com/studysparkedu" target="_blank" rel="noopener noreferrer">Поддержать на Buy Me a Coffee <ExternalLink size={16}/></a><a className="button button-outline full" href="https://t.me/StudySparkEdu" target="_blank" rel="noopener noreferrer">Наш Telegram <ExternalLink size={16}/></a></div></div>;
 if(modal.type==='purchaseSuccess')return <div className="modal-backdrop" onClick={close}><div className="modal success-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={close}><X size={18}/></button><div className="success-spark">✦</div><div className="success-emoji">{modal.reward.emoji}</div><div className="eyebrow centered">МАЛЕНЬКАЯ ПОБЕДА</div><h2>Награда получена!</h2><p>Ты обменял <b>{fmt(modal.reward.price)} ⭐</b> на<br/><strong>{modal.reward.name} {modal.reward.emoji}</strong></p><button className="button button-dark full" onClick={close}>Здорово! <Sparkles size={16}/></button></div></div>;
 if(modal.type==='manage')return <div className="modal-backdrop" onClick={close}><div className="modal manager-modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><div className="eyebrow">ТВОЯ КОЛЛЕКЦИЯ</div><h2>Управление магазином</h2></div><button className="modal-close" onClick={close}><X size={18}/></button></div><p className="form-hint">Добавляй награды, на которые приятно копить звёзды.</p><div className="manage-list">{data.rewards.map(r=><div className="manage-row" key={r.id}><span className="manage-emoji">{r.emoji}</span><div><b>{r.name}</b><small>⭐ {fmt(r.price)} · {r.category}</small></div><button className="icon-btn tiny" onClick={()=>openReward(r)}><Pencil size={15}/></button><button className="icon-btn tiny danger-hover" onClick={()=>setData(d=>({...d,rewards:d.rewards.filter(x=>x.id!==r.id)}))}><Trash2 size={15}/></button></div>)}</div><button className="button button-dark full" onClick={addReward}><Plus size={17}/> Добавить награду</button></div></div>;
 const title=modal.type==='task'?(modal.task?'Редактировать задание':'Новое задание'):modal.type==='reward'?(modal.reward?'Редактировать награду':'Новая награда'):modal.type==='profile'?'Как тебя называть?':'Настройки Pomodoro';
 return <div className="modal-backdrop" onClick={close}><div className="modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><div className="eyebrow">{modal.type==='task'?'ПЛАНИРУЙ СВОЙ УСПЕХ':modal.type==='reward'?'СОЗДАЙ МОТИВАЦИЮ':modal.type==='profile'?'ТВОЙ ПРОФИЛЬ':'ТВОЙ РИТМ'}</div><h2>{title}</h2></div><button className="modal-close" onClick={close}><X size={18}/></button></div>
 {modal.type==='profile'&&<form onSubmit={saveProfile}><p className="form-hint">Имя будет отображаться в приветствии и сохраняться на этом устройстве.</p><label>Твоё имя<input required autoFocus maxLength="40" placeholder="Например, Саша" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><button className="button button-dark full" type="submit">Сохранить имя <Check size={16}/></button></form>}
 {modal.type==='task'&&<form onSubmit={saveTask}><label>Название<input required autoFocus placeholder="Например, прочитать главу" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Описание <span>необязательно</span><textarea placeholder="Добавь немного деталей" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="form-row"><label>Сложность<select value={form.difficulty} onChange={e=>setForm({...form,difficulty:e.target.value,reward:({'Лёгкое':50,'Среднее':100,'Сложное':250,'Очень сложное':500})[e.target.value]})}><option>Лёгкое</option><option>Среднее</option><option>Сложное</option><option>Очень сложное</option></select></label><label>Награда ⭐<input type="number" min="1" value={form.reward} onChange={e=>setForm({...form,reward:e.target.value})}/></label></div><label>Дедлайн <span>необязательно</span><input type="date" value={form.due} onChange={e=>setForm({...form,due:e.target.value})}/></label><button className="button button-dark full" type="submit">{modal.task?'Сохранить изменения':'Создать задание'} <ArrowRight size={16}/></button></form>}
 {modal.type==='reward'&&<form onSubmit={saveReward}><div className="form-row reward-form-first"><label>Эмодзи<input className="emoji-input" maxLength="4" value={form.emoji} onChange={e=>setForm({...form,emoji:e.target.value})}/></label><label>Название<input required placeholder="Например, поход в кино" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label></div><label>Описание<textarea placeholder="Почему это будет приятно?" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="form-row"><label>Стоимость ⭐<input required type="number" min="1" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label><label>Категория<input placeholder="Отдых" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label></div><button className="button button-dark full" type="submit">{modal.reward?'Сохранить награду':'Добавить в магазин'} <ArrowRight size={16}/></button></form>}
 {modal.type==='settings'&&<form onSubmit={saveSettings}><p className="form-hint">Подстрой сессии под свой ритм.</p><div className="form-row"><label>Фокус, минут<input type="number" min="1" max="120" value={form.work} onChange={e=>setForm({...form,work:e.target.value})}/></label><label>Перерыв, минут<input type="number" min="1" max="60" value={form.break} onChange={e=>setForm({...form,break:e.target.value})}/></label></div><label>Звёзд за завершённый фокус<input type="number" min="1" value={form.pomoReward} onChange={e=>setForm({...form,pomoReward:e.target.value})}/></label><button className="button button-dark full" type="submit">Сохранить настройки <Check size={16}/></button></form>}</div></div>
}
createRoot(document.getElementById('root')).render(<App/>);
